server:
  port: 9093

spring:
  rabbitmq:
    host: localhost
    port: 5672
    username: user
    password: user
  datasource:
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: root
    url: jdbc:postgresql://localhost:5432/TahminDB
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
rabbitmq:
  skorqueue: skor-queue